<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ovh.mythmc</groupId>
    <artifactId>banco-bank-extension</artifactId>
    <version>0.2.0</version>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>paper-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>

        <repository>
            <id>myth-mc-snapshots</id>
            <url>https://repo.mythmc.ovh/repositories/snapshots/</url>
        </repository>

        <repository>
            <id>jitpack</id>
            <url>https://jitpack.io/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ovh.mythmc</groupId>
            <artifactId>banco-api</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>me.dablakbandit</groupId>
            <artifactId>bank</artifactId>
            <version>4.8.0-RELEASE</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/.local/bank-plugin-lite-latest-all.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>me.dablakbandit</groupId>
            <artifactId>core</artifactId>
            <version>0.6.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/.local/core-latest.jar</systemPath>
        </dependency>
    </dependencies>

</project>